name: vocsy_esys_flutter_share
description: A Flutter plugin for sharing images & text with other applications.
version: 1.0.1
repository: https://github.com/kaushikgodhani/vocsy_esys_flutter_share
homepage: https://github.com/kaushikgodhani/vocsy_esys_flutter_share

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ">=2.0.3 <3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: de.esys.esysfluttershare
        pluginClass: EsysFlutterSharePlugin
      ios:
        pluginClass: SwiftEsysFlutterSharePlugin